---
- name: Export ROCm-SMI Checks to Prometheus Metrics
  hosts: localhost
  gather_facts: yes
  vars:
    metrics_dir: /var/lib/node_exporter/textfile_collector
    metrics_file: "{{ metrics_dir }}/rocm_checks.prom"
    timestamp: "{{ ansible_date_time.epoch }}"

  tasks:
    - name: Ensure metrics directory exists
      file:
        path: "{{ metrics_dir }}"
        state: directory
        mode: '0755'
      become: yes
      check_mode: no

    - name: Check if rocm-smi exists
      command: which rocm-smi
      register: rocm_smi_check
      ignore_errors: yes
      changed_when: false
      check_mode: no

    - name: Get ROCm-SMI version
      command: rocm-smi --version
      register: rocm_version
      when: rocm_smi_check.rc == 0
      ignore_errors: yes
      changed_when: false
      check_mode: no

    - name: Get GPU information
      command: rocm-smi
      register: gpu_info
      when: rocm_smi_check.rc == 0
      ignore_errors: yes
      changed_when: false
      check_mode: no

    - name: Get detailed GPU status
      command: rocm-smi --showproductname --showfan --showtemp --showclocks
      register: gpu_status
      when: rocm_smi_check.rc == 0
      ignore_errors: yes
      changed_when: false
      check_mode: no

    - name: Prepare metrics content
      set_fact:
        metrics_content: |
          # HELP rocm_smi_installed Whether rocm-smi is installed (1=yes, 0=no)
          # TYPE rocm_smi_installed gauge
          rocm_smi_installed {{ '1' if rocm_smi_check.rc == 0 else '0' }}
          
          # HELP rocm_smi_check_timestamp Unix timestamp of the last check
          # TYPE rocm_smi_check_timestamp gauge
          rocm_smi_check_timestamp {{ timestamp }}
          
          {% if rocm_smi_check.rc == 0 %}
          # HELP rocm_smi_gpu_available Whether GPU is detected by rocm-smi (1=yes, 0=no)
          # TYPE rocm_smi_gpu_available gauge
          rocm_smi_gpu_available {{ '1' if gpu_info.rc == 0 else '0' }}
          
          {% if gpu_status.rc == 0 %}
          # Extract temperature, fan speed, and clock information if available
          {% set gpu_lines = gpu_status.stdout_lines %}
          {% for line in gpu_lines %}
          {%   if 'Temperature' in line %}
          # HELP rocm_smi_temperature_celsius GPU temperature in Celsius
          # TYPE rocm_smi_temperature_celsius gauge
          rocm_smi_temperature_celsius {{ line.split(':')[1] | regex_replace('[^0-9.]', '') }}
          {%   endif %}
          {%   if 'Fan Speed' in line %}
          # HELP rocm_smi_fan_speed_percent GPU fan speed percentage
          # TYPE rocm_smi_fan_speed_percent gauge
          rocm_smi_fan_speed_percent {{ line.split(':')[1] | regex_replace('[^0-9.]', '') }}
          {%   endif %}
          {% endfor %}
          {% endif %}
          {% endif %}

    - name: Write metrics to file
      copy:
        content: "{{ metrics_content }}"
        dest: "{{ metrics_file }}"
        mode: '0644'
      become: yes
      check_mode: no

    - name: Display ROCm-SMI Status and Metrics Location
      debug:
        msg: |
          ROCm-SMI Status Summary:
          - Binary installed: {{ rocm_smi_check.rc == 0 }}
          {% if rocm_smi_check.rc == 0 %}
          - Version info: {{ rocm_version.stdout_lines[0] | default('N/A') }}
          - GPU Available: {{ gpu_info.rc == 0 }}
          {% endif %}
          
          Metrics have been written to: {{ metrics_file }}
          
          Next steps:
          1. Ensure Node Exporter is configured to read from {{ metrics_dir }}
          2. Verify metrics are visible at http://localhost:9100/metrics
          3. Configure Prometheus server at 10.10.1.1 to scrape these metrics
